### ISSUE TITLE
网站搜索功能不可用，搜索结果点击无反应

### ISSUE THREAD

**Issue by dreadbird** [servicemesher/website#10]
![image](https://user-images.githubusercontent.com/2113395/57269177-0e23d200-70b9-11e9-8c98-3c89e6044508.png)

搜索的结果，点击任意一条，搜索框消失，但未跳转到指定文章

**Comment by rootsongjc** [comment]
@dreadbird 我试过是没问题的啊，点击搜索结果中的链接可以跳转过去。

**Comment by dreadbird** [comment]
@rootsongjc 找到原因了。。。我一直点的后面，那个“小手”迷惑了我。。。
![image](https://user-images.githubusercontent.com/2113395/57343151-bea2dc00-7174-11e9-87cc-5822845168ac.png)

**Comment by rootsongjc** [comment]
必须要点击左侧的链接才行。
