### ISSUE TITLE
Translation: Horizontal Pod Autoscaling based on custom Istio metrics

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/website#114]
## 类型

本文的类型为：翻译

## 文章信息

- 原文链接：https://banzaicloud.com/blog/k8s-hpa-prom-istio/

- 原文发布时间：2019年08月20 日

- 作者：Sandor Magyari

- 标签：Kubernetes、Istio

## 当前进度

- [x] 已有人认领翻译或为原创文章
- [x] 已提交 PR
- [x] 正在review
- [x] review 完成等待发布
- [x] 已发布到 [http://www.servicemesher.com](http://www.servicemesher.com)
- [x] 已发布到 ServiceMesher 微信公众号

**Comment by zhangsean** [comment]
assign

**Comment by rootsongjc** [comment]
@shaobai 没时间翻译，取消 assign。
