### ISSUE TITLE
Translation: Kubernetes Horizontal Pod & Cluster Autoscaling: All You Need to Know

### ISSUE THREAD

**Issue by dfang** [servicemesher/website#121]
## 类型

本文的类型为：翻译

## 文章信息

- 原文链接：https://caylent.com/kubernetes-autoscaling

- 原文发布时间：2018.10.04

- 作者：Juan Ignacio Giro

- 标签：kubernetes, autoscale

## 当前进度

- [x] 已提交文章线索
- [x] 已有人认领翻译或为原创文章
- [ ] 已提交 PR
- [ ] 正在review
- [ ] review 完成等待发布
- [ ] 已发布到 [http://www.servicemesher.com](http://www.servicemesher.com)
- [ ] 已发布到 ServiceMesher 微信公众号

**Comment by GuangmingLuo** [comment]
您好，请问翻译进度如何了？ @dfang

**Comment by dfang** [comment]
@GuangmingLuo https://github.com/servicemesher/website/pull/146
