### ISSUE TITLE
Kubernetes 上的 Service Mesh 实践：用 EnvoyFilter 扩展 Istio

### ISSUE THREAD

**Issue by cherryTML** [servicemesher/website#125]
## 类型

本文的类型为：原创

## 文章信息

- 原文链接：http://blog.ucloud.cn/archives/4189

- 原文发布时间：2019.08.27

- 作者：王昌宇

- 标签：Service Mesh、K8S

## 当前进度

- [x] 已提交文章线索
- [x] 已有人认领翻译或为原创文章
- [x] 已提交 PR
- [x] 正在review
- [x] review 完成等待发布
- [x] 已发布到 [http://www.servicemesher.com](http://www.servicemesher.com)
- [x] 已发布到 ServiceMesher 微信公众号

**Comment by cherryTML** [comment]
[Kubernetes上的Service Mesh实践：用EnvoyFilter扩展Istio_v2.1.docx](https://github.com/servicemesher/website/files/3568796/Kubernetes.Service.Mesh.EnvoyFilter.Istio_v2.1.docx)

**Comment by rootsongjc** [comment]
请参考[内容管理指南](https://github.com/servicemesher/website/blob/master/docs/content-guide.md)提交 PR，合并后将发布到官网及微信公众号。

**Comment by rootsongjc** [comment]
已完成发布，关闭 issue。
