### ISSUE TITLE
使用spring boot+kubernetes构建完整微服务平台

### ISSUE THREAD

**Issue by shinji3887** [servicemesher/website#130]
## 类型

本文的类型为：

原创

## 文章信息

- 原文链接：https://lupeier.com/post/use-kubernetes-to-build-microservices/

- 原文发布时间：2019-09-02

- 作者：陆培尔

- 标签：Kubernetes,Microservices

## 当前进度

- [x] 已提交文章线索
- [x] 已有人认领翻译或为原创文章
- [x] 已提交 PR
- [x] 正在review
- [x] review 完成等待发布
- [x] 已发布到 [http://www.servicemesher.com](http://www.servicemesher.com)
- [x] 已发布到 ServiceMesher 微信公众号

**Comment by chengwhynot** [comment]
看起来还不错，我来把这篇文章搞一个PR 合并进来

**Comment by GuangmingLuo** [comment]
文章标题是否可以斟酌一下，文章通篇更贴近两个技术栈对比与选型～
投稿请参考「投稿和贡献指南」直接提交PR即可。

**Comment by shinji3887** [comment]
> 看起来还不错，我来把这篇文章搞一个PR 合并进来

这篇是我写的，我自己提PR吧

**Comment by shinji3887** [comment]
> 文章标题是否可以斟酌一下，文章通篇更贴近两个技术栈对比与选型～
> 投稿请参考「投稿和贡献指南」直接提交PR即可。

文章对比的是spring cloud和kubernetes技术栈，spring boot是应用开发框架，不管用哪个平台都是要用到的。

**Comment by chengwhynot** [comment]
@shinji3887 已经搞了一个PR了 #131 ，你看看有啥错误可以直接修改？

**Comment by rootsongjc** [comment]
已完成发布，关闭 issue。
