### ISSUE TITLE
Translation: Kong’s Kuma Service Mesh Climbs the Kubernetes Wall

### ISSUE THREAD

**Issue by GuangmingLuo** [servicemesher/website#139]
## 类型

本文的类型为：

翻译

## 文章信息

- 原文链接：https://www.sdxcentral.com/articles/news/kongs-kuma-service-mesh-climbs-the-kubernetes-wall/2019/09/

- 原文发布时间：2019.09.11

- 作者：Dan Meyer

- 标签：service mesh

## 当前进度

- [x] 已提交文章线索
- [x] 已有人认领翻译或为原创文章
- [x] 已提交 PR
- [x] 正在review
- [x] review 完成等待发布
- [x] 已发布到 [http://www.servicemesher.com](http://www.servicemesher.com)
- [x] 已发布到 ServiceMesher 微信公众号

**Comment by rootsongjc** [comment]
已发布。
