### ISSUE TITLE
使用 Java 操作 Kubernetes API

### ISSUE THREAD

**Issue by FlyAIBox** [servicemesher/website#148]
## 类型

本文的类型为：原创

## 文章信息

- 原文链接：[https://blog.csdn.net/fly910905/article/details/101345091](url)

- 发布时间：2019年9月25日

- 作者：王延飞

- 标签：Kubernetes ，API ，Java ，Client

## 当前进度

- [x] 已提交文章线索
- [x] 已有人认领翻译或为原创文章
- [ ] 已提交 PR
- [ ] 正在review
- [ ] review 完成等待发布
- [ ] 已发布到 [http://www.servicemesher.com](http://www.servicemesher.com)
- [ ] 已发布到 ServiceMesher 微信公众号

**Comment by GuangmingLuo** [comment]
您好，投稿请提交PR。具体参考投稿指南。

**Comment by SataQiu** [comment]
ping @Fly0905 记得投稿哦！
如果实在没时间，也可以选择先暂时关闭该 Issue，有时间了再打开 :)

**Comment by FlyAIBox** [comment]
> ping @Fly0905 记得投稿哦！
> 如果实在没时间，也可以选择先暂时关闭该 Issue，有时间了再打开 :)

好的，我处理下

**Comment by rootsongjc** [comment]
长时间未投稿，关闭 issue。
