### ISSUE TITLE
Translation: The Service Mesh: What Every Software Engineer Needs to Know about the World's Most Over-Hyped Technology

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/website#176]
## 类型

本文的类型为：翻译

## 文章信息

- 原文链接：https://servicemesh.io/#intro

- 原文发布时间：2019年11月18日

- 作者：William Morgan

- 标签：Service Mesh

## 当前进度

- [x] 已提交文章线索
- [x] 已有人认领翻译或为原创文章
- [ ] 已提交 PR
- [ ] 正在review
- [ ] review 完成等待发布
- [ ] 已发布到 [http://www.servicemesher.com](http://www.servicemesher.com)
- [ ] 已发布到 ServiceMesher 微信公众号

**Comment by haiker2011** [comment]
认领

**Comment by haiker2011** [comment]
已翻译 https://www.infoq.cn/article/YYhyKSNNkOa39IKeZfjD
