### ISSUE TITLE
Translation: do-i-need-an-api-gateway-if-i-have-a-service-mesh

### ISSUE THREAD

**Issue by GuangmingLuo** [servicemesher/website#193]
## 类型

本文的类型为：

翻译

## 文章信息

- 原文链接：https://blog.christianposta.com/microservices/do-i-need-an-api-gateway-if-i-have-a-service-mesh/

- 原文发布时间：January 23, 2020

- 作者：Christian Posta

- 标签：Service Mesh, Gateway

## 当前进度

- [x] 已提交文章线索
- [x] 已有人认领翻译或为原创文章
- [ ] 已提交 PR
- [ ] 正在review
- [ ] review 完成等待发布
- [ ] 已发布到 [http://www.servicemesher.com](http://www.servicemesher.com)
- [ ] 已发布到 ServiceMesher 微信公众号

**Comment by rootsongjc** [comment]
已发布。
