### ISSUE TITLE
[feature] 增加 CI 系统

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/website#21]
使用 CircleCI 来自动集成，检查文章格式。其中格式是必须要检查的，拼写我觉得不用太严格，作为参考即可，让 CI 通过。

**Comment by chengwhynot** [comment]
目前看mdlint的有些规则也太严格，我们需要确定一个include/exclude列表。确保mdlint如果不过，就不能merge。
如果真的是过于严格，那还需要admin们手工把格式做调整？

**Comment by rootsongjc** [comment]
确实过于严格，CI 主要是给提交者以参考，毕竟这不是官方文档，只要 Markdown 最终渲染出来没问题即可。

**Comment by GuangmingLuo** [comment]
#27 
已经merge了一个相关的PR。

**Comment by SataQiu** [comment]
有更多好的想法，欢迎大家提出来！是否有更好的检查工具呢？
这个格式检查工具确实死板，需要经常调整规则。
或者咱们换个思路，只把检查的规则加进来，其他全部 exclude ？
@chengwhynot @GuangmingLuo

**Comment by chengwhynot** [comment]
我觉得可以。另外我们是不是修订一下工作流程，PR的assignee不仅负责审核译文，还要负责确保Markdown渲染正常。这两个人工过程过了，才能approve merge

**Comment by rootsongjc** [comment]
CI 已添加，关闭 issue。
