### ISSUE TITLE
[feature] 增加 CD 系统

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/website#22]
优化网站发布流程，使PR 合并后自动发布。

**Comment by chengwhynot** [comment]
我打算用netlify + github pages搞一套咱们website的CD环境

**Comment by rootsongjc** [comment]
我们目前没有使用GitHub Pages 来托管 serviemesher 网站，将来也不会，我们会使用公有云的主机来托管。

**Comment by SataQiu** [comment]
CD 功能在目前的 netlify 上应该配置下就好了吧 ？
比如把 master 作为发布分支，合并到 master 的内容自动触发 deploy
https://www.netlify.com/docs/continuous-deployment/

**Comment by chengwhynot** [comment]
比较费劲的是后续步骤。咱们这个站点需要部署到Jimmy他们公司的机器上，所以用hugo打完包后，把html部署到那台服务器上。这个netlify上面的preview，就仅供咱们approve PR前，手工review一下吧。
这样很可能用Jenkins了。
________________________________
发件人: SataQiu <notifications@github.com>
发送时间: 2019年5月27日 12:25
收件人: servicemesher/website
抄送: Cheng; Assign
主题: Re: [servicemesher/website] [feature] 增加 CD 系统 (#22)


CD 功能在目前的 netlify 上应该配置下就好了吧 ？
比如把 master 作为发布分支，合并到 master 的内容自动触发 deploy
https://www.netlify.com/docs/continuous-deployment/

―

**Comment by rootsongjc** [comment]
已完成，使用 github webhook 实现，merge 到 master 后会自动发布。
