### ISSUE TITLE
翻译：Squash, the definitive cloud-native debugging tool

### ISSUE THREAD

**Issue by haiker2011** [servicemesher/website#25]
## 类型

本文的类型为：

翻译

## 文章信息

- 原文链接：https://medium.com/solo-io/squash-the-definitive-cloud-native-debugging-tool-9d10308fe1da

- 原文发布时间：2019-03-08

- 作者：Diógenes Rettori

- 标签：Squash

## 当前进度

- [x] 已提交文章线索
- [ ] 已有人认领翻译或为原创文章
- [ ] 已提交 PR
- [ ] 正在review
- [ ] review 完成等待发布
- [ ] 已发布到 http://www.servicemesher.com
- [ ] 已发布到 ServiceMesher 微信公众号

**Comment by GuangmingLuo** [comment]
Closed due to outdated
