### ISSUE TITLE
翻译：Exploring Istio telemetry and observability

### ISSUE THREAD

**Issue by loverto** [servicemesher/website#26]
## 类型

本文的类型为：

原创

* 翻译

转载

## 文章信息

- 原文链接：https://banzaicloud.com/blog/istio-telemetry/

- 原文发布时间：2019/5/13

- 作者：Marton Sereg

- 标签：istio kubernetes service-mesh operator monitoring

## 当前进度

- [x] 已提交文章线索
- [x] 已有人认领翻译或为原创文章
- [x] 已提交 PR
- [x] 正在review
- [ ] review 完成等待发布
- [ ] 已发布到 http://www.servicemesher.com
- [ ] 已发布到 ServiceMesher 微信公众号

**Comment by chengwhynot** [comment]
认领

**Comment by chengwhynot** [comment]
merged and published.
