### ISSUE TITLE
Guidance for Building a Control Plane for Envoy Part 4 - Build for Extensibility

### ISSUE THREAD

**Issue by loverto** [servicemesher/website#37]
## 类型

本文的类型为：

原创

* 翻译

转载

## 文章信息

- 原文链接：https://blog.christianposta.com/guidance-for-building-a-control-plane-for-envoy-build-for-pluggability/

- 原文发布时间：

- 作者：Christian Posta

- 标签：envoy

## 当前进度

- [x] 已提交文章线索
- [x] 已有人认领翻译或为原创文章
- [ ] 已提交 PR
- [ ] 正在review
- [ ] review 完成等待发布
- [ ] 已发布到 http://www.servicemesher.com
- [ ] 已发布到 ServiceMesher 微信公众号

**Comment by haiker2011** [comment]
认领

**Comment by haiker2011** [comment]
@loverto http://www.servicemesher.com/blog/guidance-for-building-a-control-plane-for-envoy-part-4-build-for-extensibility/ 已翻译
