### ISSUE TITLE
[feature] 增加社区网站博客留言功能

### ISSUE THREAD

**Issue by haiker2011** [servicemesher/website#4]
是否可以考虑对现在的社区网站博客板块增加留言功能，这样大家看完博客文章之后有什么疑惑的地方，可以在文章下面留言进一步进行讨论。

**Comment by rootsongjc** [comment]
也可以，不过这样会增加一些管理成本，比如审核和管理留言。（可能会有人在留言里发广告）另外有什么留言的工具推荐吗？

**Comment by haiker2011** [comment]
对留言的工具的我也不太使用，不清楚现在主流的工具有哪些，可能需要调研一下。对于发广告，能不能借鉴邮箱的垃圾邮件过滤功能，对所有的留言进行分类，广告和垃圾留言过滤掉。:smile:

**Comment by rootsongjc** [comment]
我之前调研过搜狐的畅聊、gitment，gitment 的效果不是很好，因为是使用 GitHub issue 来保存评论的。

**Comment by chengwhynot** [comment]
试试这个？https://github.com/utterance/utterances
Jenkins中文社区好像就是用的这个

**Comment by rootsongjc** [comment]
我以前试过 [gitment](https://github.com/imsun/gitment) 与这个类似，使用 GitHub issue 来评论，网站使用的 js 有时候会影响网站加载速度。

**Comment by chengwhynot** [comment]
我先试试。我看jenkins-cn我没翻墙，访问还挺快。我先装一个试运行下？

**Comment by chengwhynot** [comment]
我好像没有权限看到settings tab，给分个试试看吧？ @rootsongjc

**Comment by shinji3887** [comment]
我自己的博客用的是gitment，感觉还可以，速度挺快的
一般看这类网站的都有github账号，解决身份认证问题，否则还要去专门注册一个评论用的账号

**Comment by rootsongjc** [comment]
需要集成下 gitment 插件

**Comment by shinji3887** [comment]
至于留言管理问题，可以基于issue里面做关键词或者敏感词的识别，发送告警邮件，这块不知道有没有什么自动化的bot能够实现

**Comment by shinji3887** [comment]
搞错了，gitment因为跨域的证书问题现在已经不能用了，我现在用的是gitalk，支持markdown语法，效果可以登录我的博客https://lupeier.com 查看，要不要我提个issue集成一下？需要先建立一个存放issues的repo

**Comment by rootsongjc** [comment]
@shinji3887 可以，提个 PR 集成下吧

**Comment by shinji3887** [comment]
> @shinji3887 可以，提个 PR 集成下吧

需要先建一个repo，用于放评论，先帮忙建一个吧，我好像没这个权限
另外需要在Developer settings->OAuth Apps中新建一个应用，并且把clientID和clientSecret给到我
用于OAuth2的用户认证，Homepage URL和Authorization callback URL都填写localhost:1313（用于测试，正式合并后填写https://www.servicemesher.com）

**Comment by rootsongjc** [comment]
@shinji3887 仓库已创建完成：https://github.com/servicemesher/gitalk

**Comment by rootsongjc** [comment]
评论功能已完成，且所有博客的初始化已完毕。
