### ISSUE TITLE
[转载] Service Mesh Interface详细介绍

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/website#42]
## 类型

本文的类型为：转载

## 文章信息

- 原文链接：https://skyao.io/post/201906-service-mesh-interface-detail/

- 原文发布时间：2019 年 6 月 5 日

- 作者：敖小剑

- 标签：

## 当前进度

- [x] 已提交文章线索
- [x] 已有人认领翻译或为原创文章
- [x] 已提交 PR
- [x] 正在review
- [x] review 完成等待发布
- [x] 已发布到 http://www.servicemesher.com
- [x] 已发布到 ServiceMesher 微信公众号

**Comment by skyao** [comment]
https://github.com/skyao/skyao.io/tree/master/content/post/201906-service-mesh-interface-detail

md文件和图片都在这里
