### ISSUE TITLE
翻译：Deep Dive into Cilium Multi-cluster

### ISSUE THREAD

**Issue by shinji3887** [servicemesher/website#58]
## 类型

本文的类型为：

翻译

## 文章信息

- 原文链接：https://cilium.io/blog/2019/03/12/clustermesh

- 原文发布时间：March 18,2019

- 作者：cilium.io

- 标签：BGP,Servicemesh

## 当前进度

- [x] 已提交文章线索
- [x] 已有人认领翻译或为原创文章
- [x] 已提交 PR
- [x] 正在review
- [x] review 完成等待发布
- [x] 已发布到 [http://www.servicemesher.com](http://www.servicemesher.com)
- [ ] 已发布到 ServiceMesher 微信公众号

**Comment by rootsongjc** [comment]
已发布：https://www.servicemesher.com/blog/deep-dive-into-cilium-multi-cluster/
