### ISSUE TITLE
[feature] 关于网站分类标签categories的建议

### ISSUE THREAD

**Issue by shinji3887** [servicemesher/website#59]
建议不要将translation设置为一个单独的分类，站在读者的角度来说
他希望看到的是按照不同的技术分门别类的文章，是不是翻译文章对读者来说区别不大
现在有大量的文章被归类到translation下，其实没有起到分类的效果
可以通过在tags下加入`translation`选项，来进行翻译文章的筛选
如下
```yaml
tags: ["service mesh","cilium","BGP","translation"]
```

**Comment by rootsongjc** [comment]
同意你的建议 @shinji3887  另外 tag 的显示及数量也还需要精简。
