### ISSUE TITLE
翻译：Layer 7 Observability with Consul Service Mesh

### ISSUE THREAD

**Issue by GuangmingLuo** [servicemesher/website#60]
## 类型

本文的类型为：

翻译

## 文章信息

- 原文链接：https://www.hashicorp.com/blog/layer-7-observability-with-consul-service-mesh

- 原文发布时间：2019/05/23

- 作者：THE CONSUL TEAM

- 标签：Consul, Service Mesh, Observability

## 当前进度

- [x] 已提交文章线索
- [x] 已有人认领翻译或为原创文章
- [x] 已提交 PR
- [x] 正在review
- [x] review 完成等待发布
- [x] 已发布到 [http://www.servicemesher.com](http://www.servicemesher.com)
- [x] 已发布到 ServiceMesher 微信公众号

**Comment by chengwhynot** [comment]
![image](https://user-images.githubusercontent.com/1076902/61030641-63999980-a3f0-11e9-867f-e0e65b20f499.png)
图里面的代码段，指定为哪种语言比较合适啊？
