### ISSUE TITLE
[feature] 文章评论初始化

### ISSUE THREAD

**Issue by SataQiu** [servicemesher/website#68]
1. 现有文章留言未初始化，还无法留言
2. 新文章留言初始化自动化

**Comment by shinji3887** [comment]
可以在admin属性中配置管理员id，有权限的用户在点击该篇blog时即可自动做评论初始化
前提：

- 该用户github为已登录状态
- 该用户对于gitalk仓库有管理员权限（可添加issue及设置label）

![image](https://user-images.githubusercontent.com/38430452/61602181-26909b00-ac6b-11e9-9111-6f2d8472419d.png)

**Comment by SataQiu** [comment]
@shinji3887 能否发布文章时就能自动初始化评论？
评论初始化能否采用文章 head 信息控制呢？比如默认是开启自动初始化评论的，如果加上 `comment: false` 就不再进行自动初始化了。这样感觉会比较灵活。

**Comment by shinji3887** [comment]
> @shinji3887 能否发布文章时就能自动初始化评论？
> 评论初始化能否采用文章 head 信息控制呢？比如默认是开启自动初始化评论的，如果加上 `comment: false` 就不再进行自动初始化了。这样感觉会比较灵活。

评论初始化本质上是使用一个github用户调用github v3 api在指定repo里面创建issue和labels
所以没法在发布文章的时候自动初始化（必须有一个登陆的github用户）
head信息的问题，本来是在每篇文章里面设置了gitalk属性的，控制每篇文章是否显示评论框
但是这样比较麻烦，所以现在我是在`config.toml`里面设置一个统一的开关`gitalk`，通过true或者false配置整站的评论功能是否开启，以应对一些可能的审查。

**Comment by rootsongjc** [comment]
所有博客评论都初始化完毕。
